### ISSUE TITLE
Offer to Help with Development

### ISSUE THREAD

**Issue by NewtonMiranda00** [Nova-Atomic/Rimworld-Together#46]
Hello,

I'm Newton Miranda, a Brazilian developer interested in offering my assistance in the development of this RimWorld mod. Although I'm not an expert in C#, I'm willing to learn and contribute in any way possible, including coding, issue resolution, testing, and documentation.

Please let me know how I can be of help and what the next steps are to get started with contributing.

Thank you!

**Comment by Nova-Atomic** [comment]
Hello and thanks for reaching out!

It's always good to have people willing to contribute into the project. As for now, all the current developers seem to be having less than the ideal time to keep up with development, so it's safe to say you could start from any place that gets your interest going.

Since you are going to be working alongside Rimworld modding system, I would recommend checking this tutorial, if you are still unfamiliar with how the method of modding, "patching", works in this game, [here](https://harmony.pardeike.net/articles/intro.html).

Don't hesitate to ask anything that might be required!

Best regards,
Nova.
